on: [push, pull_request]
name: Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: Setup Deps
      run: go get -d .
    - name: Build
      run: go build
      if: startsWith(matrix.os, 'ubuntu')
    - uses: papeloto/action-zip@v1
        with:
          files: gosessend
          dest: release-${{ matrix.artifact_name }}.zip
      if: startsWith(matrix.os, 'macos')
    - uses: papeloto/action-zip@v1
        with:
          files: gosessend
          dest: release-${{ matrix.artifact_name }}.zip
      if: startsWith(matrix.os, 'windows')
    - uses: papeloto/action-zip@v1
        with:
          files: gosessend.exe
          dest: release-${{ matrix.artifact_name }}.zip
